

INSERT INTO BOOK_CATEGORY (NAME, DESCRIPTION , CREATED_BY , CREATED_ON ) values ('Fiction','Fiction','SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK_CATEGORY (NAME, DESCRIPTION , CREATED_BY , CREATED_ON ) values ('Science Fiction','Science Fiction','SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK_CATEGORY (NAME, DESCRIPTION , CREATED_BY , CREATED_ON ) values ('Travel','Travel','SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK_CATEGORY (NAME, DESCRIPTION , CREATED_BY , CREATED_ON ) values ('Self-help/Personal','Self-help/Personal','SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK_CATEGORY (NAME, DESCRIPTION , CREATED_BY , CREATED_ON ) values ('Art','Art','SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK_CATEGORY (NAME, DESCRIPTION , CREATED_BY , CREATED_ON ) values ('Cooking','Cooking','SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK_CATEGORY (NAME, DESCRIPTION , CREATED_BY , CREATED_ON ) values ('Children’s','Children’s','SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK_CATEGORY (NAME, DESCRIPTION , CREATED_BY , CREATED_ON ) values ('History','History','SYSTEM',CURRENT_TIMESTAMP());


INSERT INTO BOOK (NAME, DESCRIPTION , AUTHOR , ISBN,  PRICE , BOOK_CATEGORY_ID , CREATED_BY , CREATED_ON ) 
values ('A Tale of Two Cities', '', 'Charles Dickens', '978-3-16-148410-0', 100,1, 'SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK (NAME, DESCRIPTION , AUTHOR , ISBN,  PRICE , BOOK_CATEGORY_ID , CREATED_BY , CREATED_ON ) 
values ('The Lord of the Rings', '', 'J.R.R. Tolkien', '978-3-16-148410-1', 120,1, 'SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK (NAME, DESCRIPTION , AUTHOR , ISBN,  PRICE , BOOK_CATEGORY_ID , CREATED_BY , CREATED_ON ) 
values ('Harry Potter and the Sorcerer’s Stone', '', 'J.K. Rowling', '978-3-16-148410-2', 120,7, 'SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK (NAME, DESCRIPTION , AUTHOR , ISBN,  PRICE , BOOK_CATEGORY_ID , CREATED_BY , CREATED_ON ) 
values ('The Da Vinci Code', '', 'Dan Brown', '978-3-16-148410-3', 120,1, 'SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK (NAME, DESCRIPTION , AUTHOR , ISBN,  PRICE , BOOK_CATEGORY_ID , CREATED_BY , CREATED_ON ) 
values ('One Hundred Years of Solitude', '', 'Gabriel García Marquez', '978-3-16-148410-4', 130,1, 'SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK (NAME, DESCRIPTION , AUTHOR , ISBN,  PRICE , BOOK_CATEGORY_ID , CREATED_BY , CREATED_ON ) 
values ('Think and Grow Rich', '', 'Napoleon Hill', '978-3-16-148410-5', 100,4, 'SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK (NAME, DESCRIPTION , AUTHOR , ISBN,  PRICE , BOOK_CATEGORY_ID , CREATED_BY , CREATED_ON ) 
values ('The Alchemist', '', 'Paulo Coelho', '978-3-16-148410-6', 140,1, 'SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK (NAME, DESCRIPTION , AUTHOR , ISBN,  PRICE , BOOK_CATEGORY_ID , CREATED_BY , CREATED_ON ) 
values ('The Runaway Bunny', '', 'Margaret Wise Brown and Clement Hurd', '978-3-16-148410-7', 70,7, 'SYSTEM',CURRENT_TIMESTAMP());
INSERT INTO BOOK (NAME, DESCRIPTION , AUTHOR , ISBN,  PRICE , BOOK_CATEGORY_ID , CREATED_BY , CREATED_ON ) 
values ('The Mitten', '', 'Jan Brett', '978-3-16-148410-8', 90,7, 'SYSTEM',CURRENT_TIMESTAMP());


INSERT INTO COUPON(CODE, DESCRIPTION , DISCOUNT_PERCENTAGE , EXPIRY_DATE  ) 
values ('MAY20','20% OFF ON FICTIONS AND CHILDRENS BOOKS', 20, '2021-05-31 11:59:00');

INSERT INTO COUPON(CODE, DESCRIPTION , DISCOUNT_PERCENTAGE , EXPIRY_DATE  ) 
values ('APR10','10% OFF ON FICTIONS AND CHILDRENS BOOKS', 10, '2021-04-30 11:59:00');


INSERT INTO COUPON(CODE, DESCRIPTION , DISCOUNT_PERCENTAGE , EXPIRY_DATE  ) 
values ('ALL15','15% OFF ON BOOKS', 15, '2021-05-31 11:59:00');


INSERT INTO COUPON(CODE, DESCRIPTION , DISCOUNT_PERCENTAGE , EXPIRY_DATE  ) 
values ('SELFHELP30','30% OFF ON SELFHELP BOOKS ', 30, '2021-05-31 11:59:00');


INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (1, 1);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (1, 7);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (2, 1);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (2, 7);

INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (3, 1);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (3, 2);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (3, 3);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (3, 4);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (3, 5);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (3, 6);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (3, 7);
INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (3, 8);

INSERT INTO COUPON_CATEGORY_MAPPING (COUPON_ID , BOOK_CATEGORY_ID ) values (4, 4);







